# If you need to modify the runtime requirements for your package,
# update the 'requirements.run' section in this file

package:
  name: "{{ PACKAGE_NAME }}"
  version: "{{ PACKAGE_VERSION }}"

source:
  path: ../src

requirements:
  build:
    - setuptools

  # Any packages required to run your package
  run:
    - numpy
    - pandas
    - foundry-transforms-lib-python

test:
  requires:

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
